import { useEffect, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Bell, Bot, Braces, Calculator, CircleStop, Clock3, Code2, FileText, GitBranch, Globe2, GripVertical, Layers3, ListTree, Network, Plus, RefreshCw, Repeat2, Save, ShieldCheck, Split, Trash2, Variable, Workflow, Wrench } from 'lucide-react';
import { useLocation, useParams } from 'wouter';
import { api } from '../lib/api';
import Button from '../components/Button';
import TextField from '../components/TextField';

const BLOCKS = [
  { type: 'tool_call', label: 'Tool call', icon: Wrench, note: 'Runs one scoped ToolGate tool with typed arguments.', value: { type: 'tool_call', tool_id: '', args: {} } },
  { type: 'set', label: 'Set value', icon: Variable, note: 'Stores a deterministic value for later workflow blocks.', value: { type: 'set', name: 'value', value: '$args.value' } },
  { type: 'calculation', label: 'Calculation', icon: Calculator, note: 'Calculates a bounded numeric result without AI.', value: { type: 'calculation', operation: 'add', values: [0, 0], save_as: 'calculation' } },
  { type: 'condition', label: 'Condition', icon: GitBranch, note: 'Chooses a nested branch using a deterministic comparison.', value: { type: 'condition', left: '$args.value', operator: 'equals', right: '', then: [], else: [] } },
  { type: 'switch', label: 'Switch', icon: Split, note: 'Selects one of several named deterministic branches.', value: { type: 'switch', value: '$args.value', cases: {}, default: [] } },
  { type: 'loop', label: 'Bounded loop', icon: Repeat2, note: 'Runs nested blocks over an array with a hard iteration ceiling.', value: { type: 'loop', items: '$args.items', item_name: 'item', max_iterations: 10, steps: [] } },
  { type: 'retry', label: 'Retry', icon: RefreshCw, note: 'Retries one nested block only for transient failures.', value: { type: 'retry', max_attempts: 2, delay_seconds: 1, step: { type: 'tool_call', tool_id: '', args: {} } } },
  { type: 'delay', label: 'Delay', icon: Clock3, note: 'Waits for a bounded number of seconds.', value: { type: 'delay', seconds: 1 } },
  { type: 'notification', label: 'Notification', icon: Bell, note: 'Creates an owner-visible update without external communication.', value: { type: 'notification', title: 'Automation update', message: 'Automation completed a stage.' } },
  { type: 'return', label: 'Return / stop', icon: CircleStop, note: 'Completes the automation with a typed result.', value: { type: 'return', value: { ok: true } } },
];
const EXECUTABLE_TYPES = ['echo', 'http_json', 'memorygate', 'ollama_generate', 'research_search', 'research_fetch'];

function Panel({ children, className = '' }) { return <div className={`rounded-xl border border-border bg-surface ${className}`}>{children}</div>; }
function Input({ className = '', ...props }) { return <input {...props} className={`mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-text outline-none focus:border-accent disabled:opacity-55 ${className}`} />; }
function stepInfo(step) { return BLOCKS.find((item) => item.type === step?.type) || { type: step?.type || 'unconfigured', label: step?.type || 'Unconfigured block', icon: Workflow, note: 'This block needs a type before the executor can run it.' }; }
function safeWorkflow(value) { return Array.isArray(value) ? value.map((step) => typeof step === 'object' && step ? step : { type: 'unconfigured', value: step }) : []; }

function ArgumentBuilder({ inputs = [], onChange, edit }) {
  function update(index, change) { onChange(inputs.map((input, current) => current === index ? { ...input, ...change } : input)); }
  return <div className="space-y-3">{inputs.length === 0 && <p className="rounded-lg border border-dashed border-border p-4 text-sm text-muted">No arguments. This automation can run without agent input.</p>}{inputs.map((input, index) => <div key={`${input.name || 'argument'}-${index}`} className="rounded-lg border border-border bg-background p-3">{edit ? <div className="grid gap-3 md:grid-cols-4"><label className="text-xs text-muted">Name<Input value={input.name || ''} onChange={(event) => update(index, { name: event.target.value })} /></label><label className="text-xs text-muted">Type<select value={input.type || 'string'} onChange={(event) => update(index, { type: event.target.value })} className="mt-1 w-full rounded-lg border border-border bg-surface p-2 text-sm text-text"><option>string</option><option>integer</option><option>number</option><option>boolean</option><option>array</option><option>object</option></select></label><label className="text-xs text-muted">Minimum<Input type="number" value={input.minimum ?? ''} onChange={(event) => update(index, { minimum: event.target.value === '' ? undefined : Number(event.target.value) })} /></label><label className="text-xs text-muted">Maximum<Input type="number" value={input.maximum ?? ''} onChange={(event) => update(index, { maximum: event.target.value === '' ? undefined : Number(event.target.value) })} /></label></div> : <div className="flex flex-wrap gap-3 text-sm"><strong>{input.name}</strong><span className="font-mono text-xs text-accent">{input.type || 'string'}</span>{input.required && <span className="text-xs text-amber-300">required</span>}</div>}{edit && <div className="mt-3 flex items-center gap-3"><label className="text-xs text-muted"><input type="checkbox" checked={Boolean(input.required)} onChange={(event) => update(index, { required: event.target.checked })} /> Required</label><button onClick={() => onChange(inputs.filter((_, current) => current !== index))} className="ml-auto text-xs text-red-400">Remove</button></div>}</div>)}{edit && <Button variant="secondary" onClick={() => onChange([...inputs, { name: 'new_argument', type: 'string', required: false }])}><Plus size={14} /> Add argument</Button>}</div>;
}

function PolicyEditor({ policy = {}, onChange, edit }) {
  const limits = policy.usage_limits || {}; const update = (change) => onChange({ ...policy, usage_limits: { ...limits, ...change } });
  return <div className="grid gap-3 md:grid-cols-2">{[['max_per_minute', 'Calls / minute'], ['max_per_hour', 'Calls / hour'], ['cooldown_seconds', 'Cooldown seconds'], ['max_runtime_seconds', 'Runtime seconds'], ['max_steps', 'Max workflow steps']].map(([key, label]) => <label key={key} className="text-xs text-muted">{label}<Input disabled={!edit} type="number" min="0" value={limits[key] ?? ''} onChange={(event) => update({ [key]: event.target.value === '' ? undefined : Number(event.target.value) })} /></label>)}</div>;
}

function JsonField({ label, value, onChange, disabled = false, rows = 4 }) {
  const [text, setText] = useState(JSON.stringify(value, null, 2));
  const [invalid, setInvalid] = useState(false);
  useEffect(() => setText(JSON.stringify(value, null, 2)), [value]);
  function update(next) {
    setText(next);
    try { onChange(JSON.parse(next)); setInvalid(false); } catch { setInvalid(true); }
  }
  return <label className="text-xs text-muted">{label}<textarea disabled={disabled} rows={rows} value={text} onChange={(event) => update(event.target.value)} className={`mt-1 w-full rounded-lg border bg-surface p-2 font-mono text-xs text-slate-300 outline-none disabled:opacity-55 ${invalid ? 'border-red-500/70' : 'border-border focus:border-accent'}`} />{invalid && <span className="mt-1 block text-[10px] text-red-400">Enter valid JSON before saving.</span>}</label>;
}

function BlockEditor({ step, index, workflow, onChange, edit, onRemove, onMove, onDragStart, onDrop }) {
  const info = stepInfo(step); const Icon = info.icon; const update = (change) => onChange(workflow.map((item, current) => current === index ? { ...item, ...change } : item));
  return <article draggable={edit} onDragStart={() => onDragStart(index)} onDragOver={(event) => event.preventDefault()} onDrop={() => onDrop(index)} className="rounded-xl border border-border bg-background p-4 transition-colors hover:border-[#303030]"><header className="flex items-center gap-2"><span className="cursor-grab text-muted active:cursor-grabbing"><GripVertical size={16} /></span><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-surface text-accent"><Icon size={16} /></span><div><div className="font-mono text-xs text-accent">{String(index + 1).padStart(2, '0')} / {info.label}</div><p className="mt-0.5 text-xs text-muted">{info.note}</p></div>{edit && <div className="ml-auto flex gap-1"><button onClick={() => onMove(index, -1)} className="rounded p-1 text-muted hover:bg-surface"><ArrowUp size={14} /></button><button onClick={() => onMove(index, 1)} className="rounded p-1 text-muted hover:bg-surface"><ArrowDown size={14} /></button><button onClick={() => onRemove(index)} className="rounded p-1 text-red-400 hover:bg-surface"><Trash2 size={14} /></button></div>}</header>
    {step.type === 'tool_call' && <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs text-muted">Tool identifier<Input disabled={!edit} value={step.tool_id || ''} placeholder="service.action" onChange={(event) => update({ tool_id: event.target.value })} /></label><label className="text-xs text-muted">Arguments JSON<textarea disabled={!edit} value={JSON.stringify(step.args || {}, null, 2)} onChange={(event) => { try { update({ args: JSON.parse(event.target.value) }); } catch {} }} className="mt-1 min-h-20 w-full rounded-lg border border-border bg-surface p-2 font-mono text-xs text-slate-300" /></label></div>}
    {step.type === 'set' && <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs text-muted">Variable name<Input disabled={!edit} value={step.name || ''} onChange={(event) => update({ name: event.target.value })} /></label><JsonField disabled={!edit} label="Value or expression" value={step.value ?? null} onChange={(value) => update({ value })} rows={2} /></div>}
    {step.type === 'calculation' && <div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs text-muted">Operation<select disabled={!edit} value={step.operation || 'add'} onChange={(event) => update({ operation: event.target.value })} className="mt-1 w-full rounded-lg border border-border bg-surface p-2 text-sm text-text"><option>add</option><option>subtract</option><option>multiply</option><option>divide</option><option>min</option><option>max</option></select></label><label className="text-xs text-muted">Save result as<Input disabled={!edit} value={step.save_as || ''} onChange={(event) => update({ save_as: event.target.value })} /></label><JsonField disabled={!edit} label="Values / expressions" value={step.values || []} onChange={(values) => update({ values })} rows={2} /></div>}
    {step.type === 'condition' && <div className="mt-4 grid gap-3 md:grid-cols-3"><JsonField disabled={!edit} label="Left value / expression" value={step.left ?? '$args.value'} onChange={(left) => update({ left })} rows={2} /><label className="text-xs text-muted">Operator<select disabled={!edit} value={step.operator || 'equals'} onChange={(event) => update({ operator: event.target.value })} className="mt-1 w-full rounded-lg border border-border bg-surface p-2 text-sm text-text"><option value="equals">equals</option><option value="not_equals">not equals</option><option value="contains">contains</option><option value="gt">greater than</option><option value="gte">greater/equal</option><option value="lt">less than</option><option value="lte">less/equal</option></select></label><JsonField disabled={!edit} label="Right value / expression" value={step.right ?? ''} onChange={(right) => update({ right })} rows={2} /><JsonField disabled={!edit} label="Then blocks" value={step.then || []} onChange={(then) => update({ then })} /><JsonField disabled={!edit} label="Else blocks" value={step.else || []} onChange={(otherwise) => update({ else: otherwise })} /></div>}
    {step.type === 'switch' && <div className="mt-4 grid gap-3 md:grid-cols-3"><JsonField disabled={!edit} label="Select value / expression" value={step.value ?? '$args.value'} onChange={(value) => update({ value })} rows={2} /><JsonField disabled={!edit} label="Cases" value={step.cases || {}} onChange={(cases) => update({ cases })} /><JsonField disabled={!edit} label="Default blocks" value={step.default || []} onChange={(fallback) => update({ default: fallback })} /></div>}
    {step.type === 'loop' && <div className="mt-4 grid gap-3 md:grid-cols-3"><JsonField disabled={!edit} label="Items / array expression" value={step.items ?? '$args.items'} onChange={(items) => update({ items })} rows={2} /><label className="text-xs text-muted">Item variable<Input disabled={!edit} value={step.item_name || 'item'} onChange={(event) => update({ item_name: event.target.value })} /></label><label className="text-xs text-muted">Maximum iterations<Input disabled={!edit} type="number" min="1" max="20" value={step.max_iterations ?? 10} onChange={(event) => update({ max_iterations: Math.min(20, Math.max(1, Number(event.target.value))) })} /></label><div className="md:col-span-3"><JsonField disabled={!edit} label="Nested blocks" value={step.steps || []} onChange={(steps) => update({ steps })} /></div></div>}
    {step.type === 'retry' && <div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs text-muted">Maximum attempts<Input disabled={!edit} type="number" min="1" max="3" value={step.max_attempts ?? 2} onChange={(event) => update({ max_attempts: Math.min(3, Math.max(1, Number(event.target.value))) })} /></label><label className="text-xs text-muted">Delay seconds<Input disabled={!edit} type="number" min="0" max="5" value={step.delay_seconds ?? 1} onChange={(event) => update({ delay_seconds: Math.min(5, Math.max(0, Number(event.target.value))) })} /></label><JsonField disabled={!edit} label="Block to retry" value={step.step || { type: 'tool_call', tool_id: '', args: {} }} onChange={(nested) => update({ step: nested })} /></div>}
    {step.type === 'delay' && <label className="mt-4 block max-w-xs text-xs text-muted">Seconds<Input disabled={!edit} type="number" min="0" max="30" value={step.seconds || 0} onChange={(event) => update({ seconds: Math.min(30, Math.max(0, Number(event.target.value))) })} /></label>}
    {step.type === 'notification' && <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs text-muted">Title<Input disabled={!edit} value={step.title || ''} onChange={(event) => update({ title: event.target.value })} /></label><label className="text-xs text-muted">Message<Input disabled={!edit} value={step.message || ''} onChange={(event) => update({ message: event.target.value })} /></label></div>}
    {step.type === 'return' && <div className="mt-4"><JsonField disabled={!edit} label="Returned value / expressions" value={step.value ?? { ok: true }} onChange={(value) => update({ value })} /></div>}
  </article>;
}

function Roadmap({ workflow }) { return <div className="overflow-x-auto p-5"><div className="flex min-w-max items-center justify-center gap-2">{workflow.length ? workflow.map((step, index) => { const info = stepInfo(step); const Icon = info.icon; return <div key={index} className="flex items-center gap-2"><div className="w-40 rounded-xl border border-border bg-background p-4"><Icon size={17} className="text-accent" /><div className="mt-3 text-sm font-medium">{info.label}</div><div className="mt-1 truncate font-mono text-xs text-muted">{step.tool_id || step.field || (step.seconds !== undefined ? `${step.seconds}s` : 'complete')}</div></div>{index < workflow.length - 1 && <div className="h-px w-10 bg-accent/50" />}</div>; }) : <p className="text-sm text-muted">Add blocks to see the execution roadmap.</p>}</div></div>; }
function LayerMap({ workflow }) { return <div className="flex min-h-[370px] items-center justify-center overflow-auto p-8"><div className="relative flex h-[310px] w-[310px] items-center justify-center rounded-full border border-accent/20 bg-accent/[0.025]">{workflow.slice(0, 4).map((step, index) => { const info = stepInfo(step); const radius = 118 - index * 25; const angle = (index / Math.max(workflow.length, 1)) * Math.PI * 2 - Math.PI / 2; return <div key={index} className="absolute flex h-14 w-14 flex-col items-center justify-center rounded-full border border-border bg-surface text-center" style={{ transform: `translate(${Math.cos(angle) * radius}px, ${Math.sin(angle) * radius}px)` }}><info.icon size={14} className="text-accent" /><span className="mt-1 max-w-12 truncate text-[9px] text-muted">{info.label}</span></div>; })}<div className="flex h-20 w-20 flex-col items-center justify-center rounded-full border border-accent/40 bg-background text-center"><Layers3 size={17} className="text-accent" /><span className="mt-1 text-[10px] text-muted">workflow</span></div></div></div>; }

function WorkflowStudio({ draft, setDraft, edit }) {
  const [view, setView] = useState('canvas'); const [dragged, setDragged] = useState(null); const [code, setCode] = useState(JSON.stringify(safeWorkflow(draft.workflow), null, 2)); const [codeError, setCodeError] = useState('');
  const workflow = safeWorkflow(draft.workflow); const setWorkflow = (value) => { setDraft({ ...draft, workflow: value }); setCode(JSON.stringify(value, null, 2)); };
  const move = (index, delta) => { const next = [...workflow]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setWorkflow(next); };
  const drop = (target) => { if (dragged === null || dragged === target) return; const next = [...workflow]; const [block] = next.splice(dragged, 1); next.splice(target, 0, block); setDragged(null); setWorkflow(next); };
  const applyCode = () => { try { const value = JSON.parse(code); if (!Array.isArray(value)) throw new Error('Workflow code must be a JSON array.'); setCodeError(''); setWorkflow(safeWorkflow(value)); } catch (error) { setCodeError(error.message); } };
  return <Panel className="overflow-hidden"><div className="border-b border-border p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-sm font-medium"><Workflow size={16} className="text-accent" /> Workflow editor</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-muted">This automation is a first-class capability: agents run its name, ToolGate executes its versioned workflow, and every layer is visible here.</p></div>{edit && <div className="flex flex-wrap gap-2">{BLOCKS.map((block) => <Button key={block.type} variant="secondary" onClick={() => setWorkflow([...workflow, structuredClone(block.value)])}><Plus size={13} /> {block.label}</Button>)}</div>}</div><div className="mt-5 flex flex-wrap gap-2">{[['canvas', Network, 'Roadmap'], ['layers', Layers3, 'Layer map'], ['blocks', ListTree, 'Blocks'], ['code', Code2, 'Code']].map(([key, Icon, label]) => <button key={key} onClick={() => setView(key)} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs ${view === key ? 'bg-accent text-white' : 'border border-border text-muted hover:bg-background hover:text-text'}`}><Icon size={14} />{label}</button>)}</div></div>
    {view === 'canvas' && <Roadmap workflow={workflow} />}{view === 'layers' && <LayerMap workflow={workflow} />}{view === 'blocks' && <div className="space-y-3 p-5">{workflow.map((step, index) => <BlockEditor key={`${step.type}-${index}`} step={step} index={index} workflow={workflow} edit={edit} onChange={setWorkflow} onRemove={(current) => setWorkflow(workflow.filter((_, itemIndex) => itemIndex !== current))} onMove={move} onDragStart={setDragged} onDrop={drop} />)}{workflow.length === 0 && <p className="rounded-lg border border-dashed border-border p-6 text-sm text-muted">No blocks yet. Use the controls above to build the automation.</p>}</div>}{view === 'code' && <div className="p-5"><p className="mb-3 text-xs text-muted">Editable JSON representation of this workflow. It maps exactly to the visual blocks; ToolGate does not accept arbitrary executable Python.</p><textarea disabled={!edit} value={code} onChange={(event) => setCode(event.target.value)} spellCheck="false" className="min-h-[380px] w-full rounded-lg border border-border bg-background p-4 font-mono text-xs leading-6 text-slate-300 outline-none focus:border-accent disabled:opacity-55" />{edit && <div className="mt-3 flex items-center gap-3"><Button onClick={applyCode}>Apply workflow code</Button>{codeError && <span className="text-xs text-red-400">{codeError}</span>}</div>}</div>}</Panel>;
}

function ToolWorkflowStudio({ draft, setDraft }) {
  const [view, setView] = useState('roadmap');
  const [code, setCode] = useState(JSON.stringify(draft.execution || {}, null, 2));
  const [codeError, setCodeError] = useState('');
  const execution = draft.execution || {};
  const updateExecution = (change) => {
    const next = { ...execution, ...change };
    setDraft({ ...draft, execution: next });
    setCode(JSON.stringify(next, null, 2));
  };
  const replaceExecution = (next) => {
    setDraft({ ...draft, execution: next });
    setCode(JSON.stringify(next, null, 2));
  };
  useEffect(() => setCode(JSON.stringify(draft.execution || {}, null, 2)), [draft.execution]);

  const pipeline = [
    { label: 'Validate inputs', detail: `${(draft.inputs || []).length} typed argument${(draft.inputs || []).length === 1 ? '' : 's'}`, icon: ShieldCheck },
    { label: execution.type === 'http_json' ? 'HTTPS request' : execution.type === 'memorygate' ? 'Memory query' : execution.type === 'ollama_generate' ? 'Local AI call' : execution.type === 'research_search' ? 'Bounded provider search' : execution.type === 'research_fetch' ? 'Provenance-bound fetch' : 'Restricted executor', detail: execution.type || 'Not configured', icon: ['http_json', 'research_search', 'research_fetch'].includes(execution.type) ? Globe2 : execution.type === 'ollama_generate' ? Bot : Wrench },
    { label: 'Extract result', detail: execution.result_path || execution.operation || (execution.type === 'echo' ? 'Echo validated input' : execution.type === 'ollama_generate' ? 'Generated text' : execution.type === 'research_search' ? 'Short-lived result handles' : execution.type === 'research_fetch' ? 'Sanitized untrusted text' : 'Not configured'), icon: Braces },
    { label: 'Return output', detail: `${(draft.outputs || []).length} declared field${(draft.outputs || []).length === 1 ? '' : 's'}`, icon: CircleStop },
  ];

  function changeType(type) {
    if (type === 'echo') {
      replaceExecution({ type: 'echo' });
      return;
    }
    if (type === 'memorygate') {
      replaceExecution({ type: 'memorygate', operation: 'context', secret_ref: 'MEMORYGATE_READ_KEY', agent_id: 'default' });
      return;
    }
    if (type === 'ollama_generate') {
      replaceExecution({ type: 'ollama_generate', prompt_template: 'Answer this focused request:\n{prompt}', model: 'qwen3:4b', temperature: 0, max_tokens: 256 });
      return;
    }
    if (type === 'research_search' || type === 'research_fetch') {
      replaceExecution({ type });
      return;
    }
    if (!type) {
      replaceExecution({});
      return;
    }
    replaceExecution({
      type: 'http_json',
      method: 'GET',
      url: execution.url || 'https://api.example.com/resource/{argument}',
      allowed_hosts: execution.allowed_hosts || ['api.example.com'],
      result_path: execution.result_path || 'result',
      timeout_seconds: execution.timeout_seconds || 10,
      max_response_bytes: execution.max_response_bytes || 262144,
    });
  }

  function applyCode() {
    try {
      const value = JSON.parse(code);
      if (!value || Array.isArray(value) || typeof value !== 'object') throw new Error('Executor code must be a JSON object.');
      setCodeError('');
      setDraft({ ...draft, execution: value });
    } catch (error) {
      setCodeError(error.message);
    }
  }

  return <Panel className="overflow-hidden">
    <div className="border-b border-border p-5">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div><h2 className="flex items-center gap-2 text-sm font-medium"><Workflow size={16} className="text-accent" /> Tool workflow</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-muted">The complete atomic execution path. ToolGate validates input first, runs one restricted adapter, extracts a typed result, and records the redacted outcome.</p></div>
        <span className={`rounded-full border px-3 py-1 text-[10px] font-medium uppercase tracking-wider ${EXECUTABLE_TYPES.includes(execution.type) ? 'border-emerald-500/25 bg-emerald-500/10 text-emerald-300' : 'border-amber-500/25 bg-amber-500/10 text-amber-300'}`}>{EXECUTABLE_TYPES.includes(execution.type) ? 'Executable' : 'Needs configuration'}</span>
      </div>
      <div className="mt-5 flex flex-wrap gap-2">{[['roadmap', Network, 'Roadmap'], ['properties', ListTree, 'Properties'], ['code', Code2, 'Code']].map(([key, Icon, label]) => <button key={key} onClick={() => setView(key)} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs ${view === key ? 'bg-accent text-white' : 'border border-border text-muted hover:bg-background hover:text-text'}`}><Icon size={14} />{label}</button>)}</div>
    </div>
    {view === 'roadmap' && <div className="overflow-x-auto p-6"><div className="flex min-w-[760px] items-stretch justify-center gap-2">{pipeline.map((step, index) => { const Icon = step.icon; return <div key={step.label} className="flex flex-1 items-center gap-2"><div className="h-full min-w-40 flex-1 rounded-xl border border-border bg-background p-4"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent/10 text-accent"><Icon size={17} /></div><div className="mt-4 text-sm font-medium">{step.label}</div><div className="mt-1 break-all font-mono text-[11px] leading-4 text-muted">{step.detail}</div></div>{index < pipeline.length - 1 && <ArrowRight size={16} className="shrink-0 text-accent/60" />}</div>; })}</div></div>}
    {view === 'properties' && <div className="grid gap-5 p-5 xl:grid-cols-2">
      <div className="rounded-xl border border-border bg-background p-4"><label className="text-xs text-muted">Restricted executor<select value={execution.type || ''} onChange={(event) => changeType(event.target.value)} className="mt-1 w-full rounded-lg border border-border bg-surface p-2 text-sm text-text"><option value="">Choose executor</option><option value="http_json">Public HTTPS JSON</option><option value="research_search">Bounded research search</option><option value="research_fetch">Provenance-bound page fetch</option><option value="memorygate">MemoryGate read-only query</option><option value="ollama_generate">Local Ollama generation</option><option value="echo">Echo validated inputs</option></select></label><p className="mt-3 text-xs leading-5 text-muted">Tools perform one atomic operation. Multi-step behavior belongs in an Automation.</p></div>
      {execution.type === 'research_search' && <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/[0.04] p-4"><h3 className="text-sm font-medium text-emerald-200">Provider-gated market search</h3><p className="mt-2 text-xs leading-5 text-muted">Searches only the declared source catalog, applies deterministic limits, marks every result as untrusted, and issues a 24-hour handle for safe follow-up reading.</p></div>}
      {execution.type === 'research_fetch' && <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/[0.04] p-4"><h3 className="text-sm font-medium text-emerald-200">No arbitrary destinations</h3><p className="mt-2 text-xs leading-5 text-muted">Accepts only a ToolGate-issued result handle. Private addresses, active content, unsafe redirects, oversized pages, and high-risk instruction payloads are blocked.</p></div>}
      {execution.type === 'http_json' && <div className="rounded-xl border border-border bg-background p-4"><div className="grid gap-3 md:grid-cols-2"><label className="text-xs text-muted md:col-span-2">HTTPS URL template<Input value={execution.url || ''} onChange={(event) => updateExecution({ url: event.target.value })} placeholder="https://api.github.com/users/{username}" /></label><label className="text-xs text-muted">Allowed hosts<Input value={(execution.allowed_hosts || []).join(', ')} onChange={(event) => updateExecution({ allowed_hosts: event.target.value.split(',').map((host) => host.trim()).filter(Boolean) })} placeholder="api.github.com" /></label><label className="text-xs text-muted">JSON result path<Input value={execution.result_path || ''} onChange={(event) => updateExecution({ result_path: event.target.value })} placeholder="public_repos" /></label><label className="text-xs text-muted">Timeout seconds<Input type="number" min="1" max="30" value={execution.timeout_seconds ?? 10} onChange={(event) => updateExecution({ timeout_seconds: Number(event.target.value) })} /></label><label className="text-xs text-muted">Maximum response bytes<Input type="number" min="1024" max="1048576" value={execution.max_response_bytes ?? 262144} onChange={(event) => updateExecution({ max_response_bytes: Number(event.target.value) })} /></label></div></div>}
      {execution.type === 'memorygate' && <div className="rounded-xl border border-border bg-background p-4"><div className="grid gap-3 md:grid-cols-2"><label className="text-xs text-muted">Operation<select value={execution.operation || 'context'} onChange={(event) => updateExecution({ operation: event.target.value })} className="mt-1 w-full rounded-lg border border-border bg-surface p-2 text-sm text-text"><option value="context">Retrieve context</option><option value="ask">Ask local memory AI</option></select></label><label className="text-xs text-muted">Agent identity<Input value={execution.agent_id || 'default'} onChange={(event) => updateExecution({ agent_id: event.target.value })} /></label><label className="text-xs text-muted md:col-span-2">Vault credential reference<Input value={execution.secret_ref || ''} onChange={(event) => updateExecution({ secret_ref: event.target.value })} placeholder="MEMORYGATE_READ_KEY" /></label></div><p className="mt-3 text-xs leading-5 text-muted">The host is fixed internally by ToolGate. This adapter cannot write, delete, or expose the credential.</p></div>}
      {execution.type === 'ollama_generate' && <div className="rounded-xl border border-border bg-background p-4"><div className="grid gap-3 md:grid-cols-3"><label className="text-xs text-muted md:col-span-3">Prompt template<textarea value={execution.prompt_template || ''} onChange={(event) => updateExecution({ prompt_template: event.target.value })} className="mt-1 min-h-28 w-full rounded-lg border border-border bg-surface p-3 text-sm text-text outline-none focus:border-accent" placeholder="Summarize this input: {prompt}" /></label><label className="text-xs text-muted">Model<Input value={execution.model || ''} onChange={(event) => updateExecution({ model: event.target.value })} placeholder="qwen3:4b" /></label><label className="text-xs text-muted">Maximum tokens<Input type="number" min="8" max="1024" value={execution.max_tokens ?? 256} onChange={(event) => updateExecution({ max_tokens: Number(event.target.value) })} /></label><label className="text-xs text-muted">Temperature<Input type="number" min="0" max="2" step="0.1" value={execution.temperature ?? 0} onChange={(event) => updateExecution({ temperature: Number(event.target.value) })} /></label></div><p className="mt-3 text-xs leading-5 text-muted">This executor uses only its declared prompt inputs and cannot access ToolGate secrets.</p></div>}
      <div className="rounded-xl border border-border bg-background p-4 xl:col-span-2"><h3 className="text-sm font-medium">Output contract</h3><p className="mb-4 mt-1 text-xs text-muted">Fields returned to the calling agent after the executor completes.</p><ArgumentBuilder inputs={draft.outputs || []} edit onChange={(outputs) => setDraft({ ...draft, outputs })} /></div>
    </div>}
    {view === 'code' && <div className="p-5"><p className="mb-3 text-xs text-muted">This typed executor definition maps exactly to the roadmap and properties. Arbitrary code is not executed.</p><textarea value={code} onChange={(event) => setCode(event.target.value)} spellCheck="false" className="min-h-[380px] w-full rounded-lg border border-border bg-background p-4 font-mono text-xs leading-6 text-slate-300 outline-none focus:border-accent" /><div className="mt-3 flex items-center gap-3"><Button onClick={applyCode}>Apply workflow code</Button>{codeError && <span className="text-xs text-red-400">{codeError}</span>}</div></div>}
  </Panel>;
}

export default function CapabilityDetailScreen({ kind }) {
  const { id } = useParams(); const [, navigate] = useLocation(); const plural = `${kind}s`;
  const [item, setItem] = useState(null); const [tab, setTab] = useState('Overview'); const [draft, setDraft] = useState(null); const [events, setEvents] = useState([]); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  useEffect(() => { api.get(`/v2/${plural}/${id}`).then((value) => { setItem(value); setDraft(value); }).catch((err) => setError(err.message)); api.get('/v2/events').then(setEvents).catch(() => {}); }, [id, plural]);
  if (error && !item) return <div className="workspace-page"><p className="text-red-400">{error}</p></div>;
  if (!item || !draft) return <div className="workspace-page text-sm text-muted">Loading {kind}...</div>;
  async function save() { setError(''); try { const updated = await api.put(`/v2/${plural}/${id}`, { ...draft, id }); setItem(updated); setDraft(updated); setSaved(true); } catch (err) { setError(err.message); } }
  async function remove() { if (!window.confirm(`Delete '${item.name}'? This cannot be undone.`)) return; try { await api.del(`/v2/${plural}/${id}`); navigate(`/${plural}`); } catch (err) { setError(err.message); } }
  const tabs = ['Overview', 'Workflow', 'Logs']; const objectEvents = events.filter((event) => event.subject_id === id);
  return <div className="workspace-page"><div className="workspace-header"><div><button onClick={() => navigate(`/${plural}`)} className="mb-4 flex items-center gap-1.5 text-xs text-muted hover:text-text"><ArrowLeft size={14} /> Back to {plural}</button><h1>{draft.name || item.name}</h1><p>{draft.description || `No description has been added for this ${kind}.`}</p></div><div className="header-actions">{saved && <span className="self-center text-xs text-green-400">Saved</span>}<Button variant="danger" onClick={remove}><Trash2 size={14} /> Delete</Button><Button variant="secondary" onClick={() => setDraft(item)}>Discard changes</Button><Button onClick={save}><Save size={14} /> Save version {item.version + 1}</Button></div></div><div className="database-summary"><div className="database-mark"><Braces size={18} /><span>{kind === 'tool' ? 'Typed capability' : 'First-class automation'}</span></div><div><strong>{item.version}</strong><span>Version</span></div><div><strong>{item.status}</strong><span>Status</span></div><div><strong>{item.authorization?.replace('_', ' ')}</strong><span>Authorization</span></div><div><strong>{kind === 'automation' ? safeWorkflow(item.workflow).length : (item.inputs || []).length}</strong><span>{kind === 'automation' ? 'Workflow layers' : 'Declared inputs'}</span></div></div><div className="database-types">{tabs.map((name) => <button key={name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}>{name}</button>)}</div>
    {tab === 'Overview' && <div className="grid gap-5 xl:grid-cols-2"><Panel className="p-5"><h2 className="mb-4 text-sm font-medium">{kind === 'automation' ? 'Automation' : 'Tool'} details</h2><div className="space-y-4"><TextField label="Name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><TextField label="Description" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /><TextField label="Stable ID" value={draft.id} disabled /><div className="grid grid-cols-2 gap-3"><label className="text-xs text-muted">Status<select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })} className="mt-1 w-full rounded-lg border border-border bg-background p-2 text-sm text-text"><option>draft</option><option>active</option><option>disabled</option></select></label><label className="text-xs text-muted">Authorization<select value={draft.authorization} onChange={(event) => setDraft({ ...draft, authorization: event.target.value })} className="mt-1 w-full rounded-lg border border-border bg-background p-2 text-sm text-text"><option value="auto">Auto</option><option value="ai_review">AI review</option><option value="owner_confirmation">Owner confirmation</option><option value="blocked">Blocked</option></select></label></div>{kind === 'automation' ? <TextField label="Schedule (optional cron)" value={draft.schedule || ''} onChange={(event) => setDraft({ ...draft, schedule: event.target.value || null })} placeholder="0 18 * * 1-5" /> : <div className="grid grid-cols-2 gap-3"><TextField label="Service ID" value={draft.service_id || ''} onChange={(event) => setDraft({ ...draft, service_id: event.target.value || null })} placeholder="github" /><TextField label="Category" value={draft.category || ''} onChange={(event) => setDraft({ ...draft, category: event.target.value })} placeholder="controlled" /></div>}</div></Panel><Panel className="p-5"><h2 className="mb-2 flex items-center gap-2 text-sm font-medium"><ShieldCheck size={15} className="text-accent" /> Execution controls</h2><p className="mb-4 text-xs text-muted">Optional deterministic limits. Empty fields do not add a limit.</p><PolicyEditor policy={draft.policy || {}} edit onChange={(policy) => setDraft({ ...draft, policy })} /></Panel><Panel className="p-5 xl:col-span-2"><h2 className="mb-2 text-sm font-medium">Input contract</h2><p className="mb-4 text-xs text-muted">Arguments supplied by an agent. Add, remove, rename, or constrain them here.</p><ArgumentBuilder inputs={draft.inputs || []} edit onChange={(inputs) => setDraft({ ...draft, inputs })} /></Panel></div>}
    {tab === 'Workflow' && (kind === 'automation' ? <WorkflowStudio draft={draft} setDraft={setDraft} edit /> : <ToolWorkflowStudio draft={draft} setDraft={setDraft} />)}
    {tab === 'Logs' && <Panel className="overflow-hidden"><div className="border-b border-border p-5"><h2 className="flex items-center gap-2 text-sm font-medium"><FileText size={15} className="text-accent" /> Execution and change history</h2><p className="mt-1 text-xs text-muted">Only redacted events tied to this {kind} appear here.</p></div>{objectEvents.length ? objectEvents.map((event) => <div key={event.id} className="border-b border-border px-5 py-4 last:border-b-0"><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{event.event_type.replaceAll('_', ' ')}</strong><span className="font-mono text-xs text-muted">{new Date(event.created_at).toLocaleString()}</span></div><p className="mt-1 text-xs text-muted">{event.severity} · {event.actor}</p></div>) : <p className="p-6 text-sm text-muted">No history for this {kind} yet.</p>}</Panel>}
    {error && <p className="text-sm text-red-400">{error}</p>}
  </div>;
}
